import type { ExperienceItem, Project, SkillCategory } from "./types";

export const PROFILE = {
  name: "Dinh Nam Nguyen",
  vietnameseName: "Nguyễn Đình Nam",
  email: "dinhnam.tech@gmail.com",
  github: "https://github.com/nguyendnam",
  location: "Ho Chi Minh City, Vietnam",
  graduation: "Expected April 2027",
  gpa: "3.0 / 4.0",
};

export const SKILL_CATEGORIES: SkillCategory[] = [
  {
    title: "Languages",
    skills: ["TypeScript", "JavaScript", "Python", "Go", "SQL", "HTML/CSS"],
  },
  {
    title: "Frontend & Mobile",
    skills: ["React", "Next.js", "React Native", "Expo", "Tailwind CSS", "Responsive UI"],
  },
  {
    title: "Backend & Data",
    skills: ["FastAPI", "Django REST", "Gin", "PostgreSQL", "MongoDB", "REST APIs"],
  },
  {
    title: "Engineering Tools",
    skills: ["Git/GitHub", "Docker", "GitHub Actions", "Sentry", "Supabase", "Clerk"],
  },
];

export const PROJECTS: Project[] = [
  {
    id: "oplang",
    eyebrow: "Developer tool · Featured",
    title: "OPLang Compiler Lite",
    description:
      "A browser-based educational compiler that exposes the complete OPLang pipeline through a typed React client and FastAPI service.",
    longDescription:
      "Built as a real product around an academic compiler: source code moves through lexing, parsing, AST generation, static semantic analysis and Jasmin generation. Compilation requests use isolated temporary directories, enforce a 100 KiB source guard and never execute generated bytecode in v1.",
    tags: ["React", "TypeScript", "FastAPI", "ANTLR", "Docker"],
    highlights: [
      "Integrated lexer, parser, AST, static checker and Jasmin generator behind one compiler facade.",
      "Added typed API handling, request cancellation, verified examples and browser persistence.",
      "Documented zero-cost deployment and an explicit security boundary for future code execution.",
    ],
    github: "https://github.com/nguyendnam/OPLang-Compiler-Lite",
    status: "v1 compile pipeline complete",
  },
  {
    id: "lostfound",
    eyebrow: "Mobile product · Team project",
    title: "HCMUT LostFound",
    description:
      "A campus lost-and-found mobile application with authenticated posting, search, filtering, media upload and direct user contact.",
    longDescription:
      "Developed and tested a proof of concept for the HCMUT community. The system combines an Expo/React Native client, Go/Gin REST API, PostgreSQL, Clerk authentication, Supabase Storage and Sentry monitoring. The team released an APK to external testers and used survey and error data to identify reliability and trust improvements.",
    tags: ["React Native", "Expo", "Go", "Gin", "PostgreSQL", "Sentry"],
    highlights: [
      "Implemented a layered mobile/backend architecture with authentication and media storage.",
      "Added CI/CD, release testing, Sentry monitoring and real-user feedback collection.",
      "Validated a real campus problem and documented next steps for SSO, push notifications and reputation.",
    ],
    github: "https://github.com/nguyendnam/HCMUT-LostFound",
    live: "https://hcmut-lostfound.github.io/landing-page/",
    status: "Proof of concept tested with users",
  },
  {
    id: "matavi",
    eyebrow: "EdTech platform · In development",
    title: "Matavi",
    description:
      "An online mathematics exam-practice platform designed around Vietnam's 2026 high-school graduation exam formats.",
    longDescription:
      "Matavi is being designed to support multiple-choice, true/false, and short-answer questions, timed exam sessions, detailed solutions, topic-level analytics and personalized practice suggestions. Current work focuses on domain modeling, question-bank structure, exam versioning, attempts, scoring and an import/review workflow for complex question content.",
    tags: ["System Design", "Question Bank", "PostgreSQL", "Go", "React"],
    highlights: [
      "Modeled question revisions, assets, exam versions, attempts, scoring and import review.",
      "Designed for math notation, diagrams, and multiple official question formats.",
      "Planned a cost-conscious deployment path using managed free tiers for the student stage.",
    ],
    status: "Architecture and implementation in progress",
  },
];

export const EXPERIENCE_ITEMS: ExperienceItem[] = [
  {
    id: "eyecode",
    role: "Frontend Developer Intern",
    company: "EyeCode Technology Solutions",
    duration: "8 weeks · Summer 2025",
    description:
      "Contributed to the administration module for an IELTS Listening Test system using Next.js, TypeScript, Tailwind CSS, and existing backend APIs.",
    highlights: [
      "Built reusable multi-step forms for full-test and per-section authoring, including audio upload and validation.",
      "Integrated create, load, detail, and edit flows with backend APIs and synchronized complex UI state.",
      "Tested the end-to-end author → view → edit workflow, improved loading/error feedback and prepared admin documentation.",
    ],
  },
  {
    id: "hcmut",
    role: "B.S. Computer Science Student",
    company: "Ho Chi Minh City University of Technology (HCMUT)",
    duration: "2022 — Expected Apr 2027",
    description:
      "Building a practical foundation across software engineering, databases, computer networks, operating systems, computer architecture, mobile development and compiler construction.",
    highlights: [
      "Current GPA: 3.0 / 4.0.",
      "Hands-on work spans web, mobile, backend services, deployment, testing and system design.",
    ],
  },
];
